server:
  port: 8088
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mytapaz_db
    username: myuser
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000 # 60 saniyə

# JWT ayarları
jwt:
  access-token-expiration-ms: 3600000     # 1 saat = 3600000 ms
  refresh-token-expiration-ms: 604800000  # 7 gün = 604800000 ms
  secret: mySuperSecretKeyThatShouldBeLongEnough123456

# Digər microservice URL nümunəsi
#client:
#  ms-birbank:
#    base-url: http://localhost:9090/birbank-api
#    timeout: 3000
